CREATE TABLE IF NOT EXISTS `tecnicos` (
  `idTecnicos` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  `logradouro` VARCHAR(100) NULL DEFAULT NULL,
  `numero` VARCHAR(10) NULL DEFAULT NULL,
  `bairro` VARCHAR(60) NULL DEFAULT NULL,
  `cidade` VARCHAR(60) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  `cep` VARCHAR(9) NULL DEFAULT NULL,
  `cargo` VARCHAR(60) NULL DEFAULT NULL,
  `situacao` ENUM('Ativo','Inativo') DEFAULT 'Ativo',
  `foto` VARCHAR(200) NULL DEFAULT NULL,
  `criado_em` DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idTecnicos`)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

ALTER TABLE `os` ADD COLUMN `tecnico_id` INT(11) NULL DEFAULT NULL;
ALTER TABLE `os` ADD INDEX `fk_os_tecnicos1` (`tecnico_id` ASC);
ALTER TABLE `os` ADD CONSTRAINT `fk_os_tecnicos1` FOREIGN KEY (`tecnico_id`) REFERENCES `tecnicos` (`idTecnicos`) ON DELETE SET NULL ON UPDATE CASCADE;
